// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfsqwbcowrcufaetzsto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpmc3F3YmNvd3JjdWZhZXR6c3RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDUxNzEsImV4cCI6MjA2MzMyMTE3MX0.hHkPGAnh3KpYMSl6dKFzt92BX6fwWcu6cxQAt5RH8Mw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);